services:
  linkding:
    container_name: linkding
    restart: unless-stopped
    image: sissbruecker/linkding:latest-plus
    ports:
      - 9090:9090
    volumes:
      - ./linkding-data:/etc/linkding/data

  linkding-pdf-archiver:
    container_name: linkding-pdf-archiver
    restart: unless-stopped
    image: ghcr.io/AdamVig/linkding-pdf-archiver:latest
    depends_on:
      linkding:
        condition: service_healthy
    environment:
      - LDPA_BASEURL=http://linkding:9090
      - LDPA_TOKEN= # Add your Linkding token
      - LDPA_TAGS=to-archive pdf
      - LDPA_SCAN_INTERVAL=3600
      - LDPA_LOG_FORMAT=text
